### ISSUE TITLE
Add Keras to SD2E Jupyter Notebooks base image

### ISSUE THREAD

**Issue by hmanz** [SD2E/jupyteruser-sd2e#13]
## Expected Behaviour

Users should be able to import Keras with the "import keras" python command. 

## Current Behaviour

Error message "ImportError: No module named keras" is outputted when trying to import keras.

## Possible Solution

pip install keras

## Steps to Reproduce (for bugs)

1. import keras
2.
3.
4.

## Context

I'm trying to create deep learning models.

## Your Environment

I don't think this is necessary for this feature request.

**Comment by zyndagj** [comment]
Do you have a preferred back end for Keras?

- Tensorflow
- CNTK
- Theano

**Comment by hmanz** [comment]
Tensorflow please. Thank you.

**Comment by zyndagj** [comment]
Tensorflow, theano, and keras are all built into the latest image. This should get pushed to production sometime Sunday.
