### ISSUE TITLE
LOCAL_ENVS does not exist

### ISSUE THREAD

**Issue by kclem** [SD2E/jupyteruser-sd2e#16]
I'm trying to follow along the instructions for loading custom conda envs into jupyter at  /examples/Advanced Jupyter.ipynb on jupyter.sd2e.org.

 However, the LOCAL_ENVS variable doesn't exist and is not defined anywhere in the page.

## Expected Behaviour
$ echo $LOCAL_ENVS
/blablabla
$

## Current Behaviour
$ echo $LOCAL_ENVS

$

## Context
This has the effect that when I try to install conda environments, I get a 
```CondaError: Unable to create prefix directory '/tabsAreGreat'.
Check that you have sufficient permissions.```
error because I can't write to /.

## Your Environment
I'm logging in to maverick if that makes a differnece.

**Comment by kclem** [comment]
Ah.. this has to be run in a jupyter bash notebook.

**Comment by zyndagj** [comment]
Correct, this will be ported to the Maverick notebooks in the near future.
