### ISSUE TITLE
Incorporate Open Probabilistic Programming Stack

### ISSUE THREAD

**Issue by zyndagj** [SD2E/jupyteruser-sd2e#2]
Hello,

We are interested in supporting the Open Probabilistic Programming Stack into the base Jupyter image to use BaysDB.

## Expected Behavior

* Run the notebooks included in the probcomp/stack-release:0.3.1 docker image found at http://probcomp.org/open-probabilistic-programming-stack/ in a **python2** kernel.
  * gapminder-exploratory.ipynb
  * gapminder-missing-data.ipynb
  * introduction.ipynb
  * satellites-predictive.ipynb

## Current Behavior

* Notebooks are not present
* Necessary dependencies are not present

## Possible Solution

* Install the necessary build depencies
  * libboost-all-dev
  * libgsl0-dev
  * ccache
* Install the necessary python libraries
  * https://github.com/probcomp/Venturecxx/archive/v0.5.1a20170816.tar.gz
  * git+https://github.com/probcomp/cgpm.git@v0.1
  * git+https://github.com/probcomp/crosscat.git@v0.1.56
  * git+https://github.com/probcomp/bayeslite.git@v0.3.1
  * git+https://github.com/probcomp/iventure.git@v0.2
* Grab notebooks and resources from probcomp/stack-release:0.3.1 image

## Context

This software is necessary our collaborators from the MIT Probabilistic Computing Project lab.

**Comment by mwvaughn** [comment]
Looks like this works in my merge. Will push out to production Monday morning for testing.
