### ISSUE TITLE
Quick look dependencies request

### ISSUE THREAD

**Issue by meslami-netrias** [SD2E/jupyteruser-sd2e#3]
Need a few dependencies installed when you all can.

--> plotly, igraph, and networkx. 

I need these to be able to run my quick look notebooks in the Jupyter hub.

Note that igraph in python also has some dependencies in C that might need to be installed. I did it so long ago I forget...

**Comment by mwvaughn** [comment]
Resolved. Will release to production Monday. Let us know if these don't work as intended.

**Comment by meslami-netrias** [comment]
@mwvaughn just tested my notebook after a Jupyter server restart. It can't find the dependencies when I try to import them.
