### ISSUE TITLE
Common Lisp Kernel

### ISSUE THREAD

**Issue by mdehavensift** [SD2E/jupyteruser-sd2e#5]
We would like to add the Common Lisp kernel to the Jupyter notebooks.

## Expected Behaviour
Common Lisp should be one of the available kernel options when creating a new notebook when using the SD2 Jupyter notebook Docker container.

## Current Behaviour
Currently, there is no support for Common Lisp in the Jupyter notebook Docker image.

## Possible Solution
Install the Common Lisp kernel (https://github.com/fredokun/cl-jupyter).

## Context
SIFT's code is written in Common Lisp. We would like to be able to easily share examples with other people on the project in a way that is interactive and familiar to most people. We think that using Jupyter notebooks would be a good solution because they are interactive and, while many people on the project may not be familiar with Common Lisp, most will be familiar with Jupyter notebooks and will be using them to some extent for other parts of the project. Integrating the Common Lisp kernel into the existing SD2 Jupyter notebook image will allow us to easily share examples in a way that other's will be able access and run conveniently.

**Comment by zyndagj** [comment]
I'll test your integration tomorrow and hopefully work towards integration.

**Comment by zyndagj** [comment]
After some non-deterministic errors caused by my docker cache and making sure the `jupyter` user could write to `/home/jupyter/.jupyter/` as shown
```
gzynda@js-104-201:~/Documents/jupyteruser-sd2e$ sudo docker run -it sd2e/jupyteruser-sd2e:devel bash
@06115df5235a:~$ touch .jupyter/migrated
@06115df5235a:~$ whoami
jupyter
```

I keep encountering the same error when trying to launch the notebook
```
gzynda@js-104-201:~/Documents/jupyteruser-sd2e$ (cd test && sudo docker-compose up)
Starting jupyter ...
Starting jupyter ... done
Attaching to jupyter
jupyter    | Traceback (most recent call last):
jupyter    |   File "/opt/conda/bin/jupyter-notebook", line 6, in <module>
jupyter    |     sys.exit(notebook.notebookapp.main())
jupyter    |   File "/opt/conda/lib/python3.5/site-packages/jupyter_core/application.py", line 267, in launch_instance
jupyter    |     return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
jupyter    |   File "/opt/conda/lib/python3.5/site-packages/traitlets/config/application.py", line 595, in launch_instance
jupyter    |     app.initialize(argv)
jupyter    |   File "<decorator-gen-7>", line 2, in initialize
jupyter    |   File "/opt/conda/lib/python3.5/site-packages/traitlets/config/application.py", line 74, in catch_config_error
jupyter    |     return method(app, *args, **kwargs)
jupyter    |   File "/opt/conda/lib/python3.5/site-packages/notebook/notebookapp.py", line 1290, in initialize
jupyter    |     super(NotebookApp, self).initialize(argv)
jupyter    |   File "<decorator-gen-6>", line 2, in initialize
jupyter    |   File "/opt/conda/lib/python3.5/site-packages/traitlets/config/application.py", line 74, in catch_config_error
jupyter    |     return method(app, *args, **kwargs)
jupyter    |   File "/opt/conda/lib/python3.5/site-packages/jupyter_core/application.py", line 243, in initialize
jupyter    |     self.migrate_config()
jupyter    |   File "/opt/conda/lib/python3.5/site-packages/jupyter_core/application.py", line 169, in migrate_config
jupyter    |     migrate()
jupyter    |   File "/opt/conda/lib/python3.5/site-packages/jupyter_core/migrate.py", line 241, in migrate
jupyter    |     with open(os.path.join(env['jupyter_config'], 'migrated'), 'w') as f:
jupyter    | PermissionError: [Errno 13] Permission denied: '/home/jupyter/.jupyter/migrated'
jupyter exited with code 1
```
The container works without your patch, and I have also gotten good about removing all my docker images. Were you able to run the container and launch a lisp kernel?

@mwvaughn Can you reproduce?

**Comment by mdehavensift** [comment]
Yes, I was able to launch the container and the lisp kernel and
everything worked. I looked at my permissions and the test/dotjupyter
directory, which gets mounted to /home/jupyter/.jupyter, had write
permissions for everyone, as below:

drwxrwxrwx 2 matthew matthew 4096 Nov 30 15:47 dotjupyter

I took away the write permissions, and I got the same error as you.

drwxr-xr-x 2 matthew matthew 4096 Nov 30 15:47 dotjupyter

Also, with the write permissions taken away, I ran the same process you
listed, and I could create the file still.

matthew@debian:~/projects/sd2/jupyteruser-sd2e/test$ docker run -it
sd2e/jupyteruser-sd2e:devel bash
@8f50cb24c44d:~$ touch .jupyter/migrated
@8f50cb24c44d:~$ whoami
jupyter

So I'm not sure how it can be that the file can be created from bash but
the python process is failing. I'll try to look into this more.

-- Matthew

**Comment by zyndagj** [comment]
Nice!

I didn't even think about changing the permissions of that folder outside of the container. After

```
gzynda@js-104-201:~/Documents/jupyteruser-sd2e/test$ chmod a+w dotjupyter
```

Your kernel seems to work fine

```
gzynda@js-104-201:~/Documents/jupyteruser-sd2e$ (cd test && sudo docker-compose                               up)
Starting jupyter ...
Starting jupyter ... done
Attaching to jupyter
jupyter    | [I 22:49:15.955 NotebookApp] Writing notebook server cookie secret                               to /home/jupyter/.local/share/jupyter/runtime/notebook_cookie_secret
jupyter    | [W 22:49:15.974 NotebookApp] WARNING: The notebook server is listen                              ing on all IP addresses and not using encryption. This is not recommended.
jupyter    | [I 22:49:15.984 NotebookApp] Serving notebooks from local directory                              : /home/jupyter
jupyter    | [I 22:49:15.984 NotebookApp] 0 active kernels
jupyter    | [I 22:49:15.984 NotebookApp] The Jupyter Notebook is running at: ht                              tp://[all ip addresses on your system]:8888/
jupyter    | [I 22:49:15.985 NotebookApp] Use Control-C to stop this server and                               shut down all kernels (twice to skip confirmation).
```

I can also confirm that

```
(print "hello")
```

worked inside a SBCL Lisp notebook. I will talk with MattV about updating those permissions.

**Comment by zyndagj** [comment]
@mdehavensift Your branch has now been pushed to our staging environment and I also fixed the permission issue that originally confused me.

Can you please confirm that your kernel and examples work at

https://jupyter-staging.sd2e.org/

Thanks!

**Comment by mdehavensift** [comment]
@zyndagj I cannot access that page. It says I'm unable to connect.

**Comment by mdehavensift** [comment]
@zyndagj I was able to access the the staging area and tested the common lisp kernel. Everything works as expected.

**Comment by zyndagj** [comment]
Awesome, thanks!

@mwvaughn it looks like this is ready for integration into master
